

fadeup

Copyright (c) 2000, LucasArts Entertainment Company LLC
VERSION 0.1

actor bob

script "makepowerup"
{

PauseRandom 1 10

RandomInt dice1 1 9


                 if (= dice1 1)
                {
                CreateActor powerupinvulnerable.dsc bob hidden
                }
                   
                 if (= dice1 2)
                {
                CreateActor poweruphealth.dsc bob hidden
                }
         
                 if (= dice1 3)
                {
                CreateActor poweruphealth.dsc bob hidden
                }

                if (= dice1 4)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }

                if (= dice1 5)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }
        
                if (= dice1 6)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }
         
                if (= dice1 7)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }
        
                if (= dice1 8)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }
           
                if (= dice1 9)
                {
                CreateActor powerupunlimitedforce.dsc bob hidden
                }
                
 pause 2
 RandomInt dice2 1 5  

    if (= dice2 1)
        {
        Teleport bob pu1
        }

    if (= dice2 2)
        {
        Teleport bob pu2
        }

        if (= dice2 3)
        {
        Teleport bob pu3
        }
    if (= dice2 4)
        {
        Teleport bob pu4
        }
    if (= dice2 5)
        {
        Teleport bob pu5
        }

WaitUntilRemoved bob
loop
}


















